version: "3.3"

services:
  accruals-balance-calculator:
    image: maven:3.8.3-openjdk-17
    entrypoint:
      [
        "mvn",
        "spring-boot:run",
        "-Duser.home=/Users/1000",
        "-Duser.name=1000",
        "-Dspring-boot.run.jvmArguments=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=*:5005",
      ]

    user: "1000"
    working_dir: "/app"
    ports:
      - "50210:9090"
      - "50211:5005"
    volumes:
      - ./:/app
      - $HOME/.m2:/Users/1000/.m2 # Required for artifactory dependencies
      - keystore:/keystore
    environment:
      - HOME=/Users/1000
      - MAVEN_USER_HOME=/Users/1000/.m2
      - SPRING_PROFILES_ACTIVE=localdev
      - BOOTSTRAP_SERVER=kafka:9093
      - KEYSTORE_LOCATION=file://keystore/kafka/kafka.keystore.jks
      - TRUSTSTORE_LOCATION=file://keystore/kafka/kafka.truststore.jks
      - BALANCE_CALCULATOR_KEYSTORE_PASSWORD=changeit
    networks:
      - callisto

networks:
  callisto:
    name: callisto-localdev_callisto
    driver: bridge
    external: true

volumes:
  keystore:
    name: callisto-localdev_keystore
    external: true
