version: "3.3"

services:
  REPLACE-SERVICE-NAME:
    image: maven:3.8.3-openjdk-17
    entrypoint:
      [
        "mvn",
        "spring-boot:run",
        "-Duser.home=/Users/1000",
        "-Duser.name=1000",
        "-Dspring-boot.run.jvmArguments=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=*:5005",
      ]

    user: "1000"
    working_dir: "/app"
    ports:
      - "REPLACE-LOCAL-PORT:9090"
      - "5005:5005"
    volumes:
      - ./:/app
      - $HOME/.m2:/Users/1000/.m2 # Required for artifactory dependencies
    environment:
      - HOME=/Users/1000
      - MAVEN_USER_HOME=/Users/1000/.m2
      - SPRING_PROFILES_ACTIVE=localdev
    networks:
      - callisto

networks:
  callisto:
    name: callisto-localdev_callisto
    driver: bridge
    external: true
