image:
  repository: quay.io/ukhomeofficedigital/callisto-balance-calculator
  tag: latest
  pullPolicy: Always

service:
  port: 9090

kafka:
  defaultTopic: callisto-timecard-timeentries
  identity: balance-calculator
  mskSecretKeyRefName: callisto-prod-msk
  bootstrapSecretKeyRefName: callisto-prod-bootstrap