image:
  repository: quay.io/ukhomeofficedigital/callisto-balance-calculator
  tag: latest
  pullPolicy: Always

service:
  port: 9090

deploymentAnnotations:
  downscaler/uptime: Mon-Fri 08:00-20:00 Europe/London

kafka:
  defaultTopic: callisto-timecard-timeentries
  identity: balance-calculator
  mskSecretKeyRefName: callisto-test-msk
  bootstrapSecretKeyRefName: callisto-test-bootstrap