name: Balance Calculator Maven build
on:
  push:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@main
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build Service
        run: |
          echo $GITHUB_ACTOR
          mvn -s ./balance_calculator_settings.xml clean install
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
